--- 
abstract: Just Parse robots.txt
author: Copyright (c) 2006-2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-RobotRules-Parser
no_index: 
  directory: 
    - inc
    - t
requires: 
  LWP::UserAgent: 0
  URI: 0
version: 0.04
